name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        auto-activate-base: false
        channels: conda-forge

    - name: Install dependencies
      run: mamba install pybind11 nlohmann_json pybind11_json pytest pip

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
        cd dist
        sha256sum * | tee SHA256SUMS

    - name: Install the package
      run: pip install -vv xjson*.whl
      working-directory: dist

    - name: Run pytest
      run: pytest . -vvv
